codecov:
  token: add2ebe0-11ce-4a7a-a3bb-1223d1c6e0bd
  bot: "codecov-io"
  ci:
    - "circleci.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
